name: Build C++ EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: CMake konfigurieren
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Projekt kompilieren (Release)
      run: cmake --build build --config Release

    - name: EXE als Download bereitstellen
      uses: actions/upload-artifact@v4
      with:
        name: Universal-No-Recoil-EXE
        path: |
          build/Release/*.exe
          build/*.exe
