name: Build C++ EXE

on:
  workflow_dispatch: # Ermöglicht den manuellen Start per Knopfdruck

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Visual Studio Build Tools einrichten
      uses: microsoft/setup-msbuild@v2

    - name: Projekt kompilieren (Release x64)
      run: msbuild Universal-No-Recoil.sln /p:Configuration=Release /p:Platform=x64

    - name: EXE als Download bereitstellen
      uses: actions/upload-artifact@v4
      with:
        name: Universal-No-Recoil-EXE
        path: x64/Release/
